Cypress.Commands.add('setArticleChoice', (article, color, size) => {
    cy.request('http://shop.demoqa.com/')
    cy.contains(article).click({ force: true })
    cy.get('#pa_color').select(color)
    cy.get('#pa_size').select(size)

})

Cypress.Commands.add('setPersonnalInformations', (firstName, lastName, country, adress, additionalAdress, postCode, city, phone, email) => {
    cy.get('#billing_first_name').type(firstName)
        .should('have.value', firstName)
    cy.get('#billing_last_name').type(lastName)
        .should('have.value', lastName)
    cy.get('#select2-billing_country-container').click().type(country + '{enter}')
    cy.get('#billing_address_1').clear().type(adress)
        .should('have.value', adress)
    cy.get('#billing_address_2').clear().type(additionalAdress)
        .should('have.value', 'Appt 26')
    cy.get('#billing_postcode').clear().type(postCode)
        .should('have.value', postCode)
    cy.get('#billing_city').clear().type(city)
        .should('have.value', city)
    cy.get('#billing_phone').clear().type(phone)
        .should('have.value', phone)
    cy.get('#billing_email').clear().type(email)
        .should('have.value', email)
    cy.get('#terms').check()
})